main: "cc.dreamcode.warp.WarpPlugin"
version: "1.0-InDEV"
name: "Dream-Warp"
description: "Dream-Warp plugin written by dreamcode.cc"
website: "https://dreamcode.cc"
author: "author"
api-version: 1.13